alt_send_esc: true

window:
  dynamic_title: true
  dimensions:
    columns: 240
    lines: 60

scrolling:
  history: 0

font:
  normal:
    family: JetbrainsMono Nerd Font
    # family: ProggyCleanTTSZ Nerd Font Mono
  size: 12
  # size: 15

env:
  # https://github.com/jwilm/alacritty/issues/2566
  LC_CTYPE: en_US.UTF-8

key_bindings:
  - key: N
    mods: Command
    action: SpawnNewInstance
  # https://github.com/alacritty/alacritty/issues/623
  - key: A
    mods: Alt
    chars: "\x1ba"
  - key: A
    mods: Alt|Shift
    chars: "\x1bA"
  - key: B
    mods: Alt
    chars: "\x1bb"
  - key: B
    mods: Alt|Shift
    chars: "\x1bB"
  - key: C
    mods: Alt
    chars: "\x1bc"
  - key: C
    mods: Alt|Shift
    chars: "\x1bC"
  - key: D
    mods: Alt
    chars: "\x1bd"
  - key: D
    mods: Alt|Shift
    chars: "\x1bD"
  - key: F
    mods: Alt
    chars: "\x1bf"
  - key: F
    mods: Alt|Shift
    chars: "\x1bF"
  - key: G
    mods: Alt
    chars: "\x1bg"
  - key: G
    mods: Alt|Shift
    chars: "\x1bG"
  - key: H
    mods: Alt
    chars: "\x1bh"
  - key: H
    mods: Alt|Shift
    chars: "\x1bH"
  - key: I
    mods: Alt
    chars: "\x1bi"
  - key: I
    mods: Alt|Shift
    chars: "\x1bI"
  - key: J
    mods: Alt
    chars: "\x1bj"
  - key: J
    mods: Alt|Shift
    chars: "\x1bJ"
  - key: K
    mods: Alt
    chars: "\x1bk"
  - key: K
    mods: Alt|Shift
    chars: "\x1bK"
  - key: L
    mods: Alt
    chars: "\x1bl"
  - key: L
    mods: Alt|Shift
    chars: "\x1bL"
  - key: M
    chars: "\x1bm"
    mods: Alt
  - key: M
    mods: Alt|Shift
    chars: "\x1bM"
  - key: N
    mods: Alt
    chars: "\x1bn"
  - key: N
    mods: Alt|Shift
    chars: "\x1bN"
  - key: O
    mods: Alt
    chars: "\x1bo"
  - key: O
    mods: Alt|Shift
    chars: "\x1bO"
  - key: P
    mods: Alt
    chars: "\x1bp"
  - key: P
    mods: Alt|Shift
    chars: "\x1bP"
  - key: Q
    mods: Alt
    chars: "\x1bq"
  - key: Q
    mods: Alt|Shift
    chars: "\x1bQ"
  - key: R
    mods: Alt
    chars: "\x1br"
  - key: R
    mods: Alt|Shift
    chars: "\x1bR"
  - key: S
    mods: Alt
    chars: "\x1bs"
  - key: S
    mods: Alt|Shift
    chars: "\x1bS"
  - key: T
    mods: Alt
    chars: "\x1bt"
  - key: T
    mods: Alt|Shift
    chars: "\x1bT"
  - key: U
    mods: Alt
    chars: "\x1bu"
  - key: U
    mods: Alt|Shift
    chars: "\x1bU"
  - key: V
    mods: Alt
    chars: "\x1bv"
  - key: V
    mods: Alt|Shift
    chars: "\x1bV"
  - key: W
    mods: Alt
    chars: "\x1bw"
  - key: W
    mods: Alt|Shift
    chars: "\x1bW"
  - key: X
    mods: Alt
    chars: "\x1bx"
  - key: X
    mods: Alt|Shift
    chars: "\x1bX"
  - key: Y
    mods: Alt
    chars: "\x1by"
  - key: Y
    mods: Alt|Shift
    chars: "\x1bY"
  - key: Z
    mods: Alt
    chars: "\x1bz"
  - key: Z
    mods: Alt|Shift
    chars: "\x1bZ"
  - key: Slash
    mods: Alt
    chars: "\x1b/"

# Colors (Pastel - Dark Background)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#fefefe'

  # Cursor colors
  cursor:
    text: '#feffff'
    cursor: '#abd2fe'

  # Selection colors
  selection:
    text: '#c7c7c7'
    background: '#456d95'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff8272'
    green:   '#b4fa72'
    yellow:  '#fefdc2'
    blue:    '#a5d5fe'
    magenta: '#ff8ffd'
    cyan:    '#d0d1fe'
    white:   '#f1f1f1'

  # Bright colors
  bright:
    black:   '#8c8c8c'
    red:     '#ffc4bd'
    green:   '#d6fcb9'
    yellow:  '#fefdd5'
    blue:    '#c1e3fe'
    magenta: '#ffb1fe'
    cyan:    '#a3a8fe'
    white:   '#feffff'
